// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cpp_serialize_pb
Rcpp::RawVector cpp_serialize_pb(Rcpp::RObject x);
RcppExport SEXP protolite_cpp_serialize_pb(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    __result = Rcpp::wrap(cpp_serialize_pb(x));
    return __result;
END_RCPP
}
// cpp_unserialize_pb
Rcpp::RObject cpp_unserialize_pb(Rcpp::RawVector x);
RcppExport SEXP protolite_cpp_unserialize_pb(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type x(xSEXP);
    __result = Rcpp::wrap(cpp_unserialize_pb(x));
    return __result;
END_RCPP
}
