# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_serialize_pb <- function(x, skip_native) {
    .Call('protolite_cpp_serialize_pb', PACKAGE = 'protolite', x, skip_native)
}

cpp_unserialize_pb <- function(x) {
    .Call('protolite_cpp_unserialize_pb', PACKAGE = 'protolite', x)
}

